### PR TITLE
eval report from 2/09 and 2/16

### PR DESCRIPTION
**Pull request by eycramer**

### CODE REVIEW

**Comment by hannanabdul55** [comment]
@eycramer @mzorn-58 - can we use a separate folder for this? Something like `eval-reports` maybe?  This would help distinguish the URL for these reports too (they'd be like https://covid19forecasthub.org/eval-reports/...).

**Comment by mzorn-58** [comment]
Sounds like a good idea.

**Comment by hannanabdul55** [comment]
Also, would there be state-wise evaluation reports too?

**Comment by mzorn-58** [comment]
Wouldn't we want to put them inn the web repo?  https://covid19forecasthub**web**.org/eval-reports/

**Comment by hannanabdul55** [comment]
Yes, it would be in the web repo.

**Pull request merged**
